server.port=8082
spring.application.name=hrms

# --- TURN OFF TEMPORARY H2 DATABASE ---
# spring.datasource.url=jdbc:h2:mem:hrmsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=root
# spring.datasource.password=root
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# --- TURN ON PERMANENT MYSQL WORKBENCH DATABASE ---
spring.datasource.url=jdbc:mysql://localhost:3306/hrms_db?useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# This tells Hibernate to build your appraisal tables inside MySQL automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Disable the Thymeleaf template folder check (if you aren't using server-side HTML templates)
spring.thymeleaf.check-template-location=false

# Disable OSIV to optimize database connection pool usage
spring.jpa.open-in-view=false